import React from "react";
import { Container, Row } from "react-bootstrap";
import Banner1 from "../public/assets/aboutus/banner1.png";
import Banner2 from "../public/assets/aboutus/banner2.png";
import About1 from "../public/assets/aboutus/About1.png";
import About2 from "../public/assets/aboutus/About2.png";
import About3 from "../public/assets/aboutus/About3.png";
import About4 from "../public/assets/aboutus/About4.png";
import Image from "next/image";

const data = [
  {
    id: 1,
    photo: About1,
  },
  {
    id: 2,
    photo: About2,
  },
  {
    id: 3,
    photo: About3,
  },
  {
    id: 4,
    photo: About4,
  },
];

const Aboutus = () => {
  return (
    <section>
      <Container fluid>
        <Row className="">
          <div className="p-0 col-md-12  col-lg-12 position-relative">
            <div>
              <Image
                alt="portfolio banner"
                src={Banner1}
                className="img-fluid w-100"
              />
            </div>
            <div
              className="position-absolute  top-50 start-50 translate-middle"
              style={{ color: "white" }}
            >
              <h1>About us</h1>
            </div>
            <div
              className="position-absolute bottom-0 start-0 mb-3"
              style={{ color: "white" }}
            >
              <h4 className="ms-5 ps-5">Home/Portfolio/About us</h4>
            </div>
          </div>
        </Row>
      </Container>
      <Container>
        <Row className="py-5">
          <h2 className="ps-0">ABOUT OUR COMPANY</h2>
          <div className="col-md-12 col-lg-12 p-0">
            <p className="lh-lg pb-3">
              Think space Service is a full service, interior design firm based
              in Australia specializing in classic design with a global
              influence. whether designing residential or commercial spaces, KCD
              has built a reputation on achieving highly individual results for
              a discerning, international clientele.
            </p>
            <p className="lh-lg pb-3">
              Think Space Service crafts visual stories that become signature
              surroundings. Guided by client’s aspirations, as well as their
              diverse experiences., the firm designs singular interiors, which
              allows clients to fully express who they are, and what holds
              meaning to them.
            </p>{" "}
            <p className="lh-lg">
              The history and location of the project, coupled with Think Space
              Service’s broad base of experience, and its firm belief that
              successful design must be generated by the individual
              characteristics of each project, let’s Think Space Service create
              extraordinary interiors. A portfolio of completed work includes
              historic restorations, contemporary renovations and our
              construction projects.
            </p>
          </div>
          <div className="col-md-11 col-lg-11 p-0">
            <h3 className="pb-3">Our Aim/ Mission and Value</h3>
            <p className="lh-lg">
              Our Aim is a full service, interior design firm based in Australia
              specializing in classic design with a global influence. whether
              designing residential or commercial spaces, KCD has built a
              reputation on achieving highly individual results for a
              discerning, international clientele.
            </p>
          </div>
          <div className="col-md-12 col-lg-12 py-5 p-0">
            <Image
              src={Banner2}
              className="img-fluid w-100"
              alt="about us img"
            />
          </div>
          <div className="col-md-12 col-lg-12 p-0">
            <div className="d-flex justify-content-between">
              <div className="d-flex justify-content-start">
                <h2>MEET OUR TEAM</h2>
              </div>
              <div className="d-flex justify-content-end">
                {" "}
                <div className="projectbutton  btn p-2 shadow-sm border border-black border-opacity-25 text-primary rounded-0">
                  <span className="px-2 fw-medium" style={{ fontSize: "16px" }}>
                    LEARN MORE
                  </span>
                  <span className="p-1 ps-1">
                    <i class="bi bi-arrow-right"></i>
                  </span>
                </div>
              </div>
            </div>
            <div className="col-md-12 col-lg-12 p-0 d-flex">
              {data?.map((items, index) => (
                <div key={index} class="card col-md-3 col-lg-3  ">
                  <Image
                    src={items.photo}
                    className="img-fluid"
                    alt="card images"
                  />
                  <div class="card-body">
                    <h5 class="card-title">Card title</h5>
                    <p class="card-text">
                      Some quick example text to build on the card title and
                      make up the bulk of the card's content.
                    </p>
                    <a href="#" class="btn btn-primary">
                      Go somewhere
                    </a>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </Row>
      </Container>
    </section>
  );
};

export default Aboutus;
